'use strict';
const root=document.querySelector('#app'),dialogs=document.querySelector('#dialogs'),notices=document.querySelector('#notices');
let session=null,data=null,tap=null,view='Overview',filters={store_id:'',user_id:'',from:'',to:''},pending=null,loading=false,page=0,modal=null,lastLocation=null;
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(stamp,tz='Australia/Sydney',date=false)=>stamp==null?'—':new Date(stamp*1000).toLocaleString('en-AU',{timeZone:tz,...(date?{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}:{hour:'2-digit',minute:'2-digit'})});
const hours=n=>(n/3600).toFixed(2),displayDuration=n=>Math.floor(n/3600)+'h '+Math.floor(n%3600/60)+'m '+Math.floor(n%60)+'s';
const employee=id=>data?.users.find(u=>u.id===id),store=id=>data?.stores.find(s=>s.id===id);
const isManager=()=>session?.user?.role!=='staff',isOwner=()=>session?.user?.role==='owner';
function flash(message,error=false){notices.innerHTML=`<div class="alert ${error?'error':''}" role="${error?'alert':'status'}">${h(message)}</div>`;if(!error)setTimeout(()=>notices.replaceChildren(),7000)}
async function api(path,payload){
 const options=payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session?.csrf||''},body:JSON.stringify(payload)};
 let response;try{response=await fetch(path,{...options,signal:AbortSignal.timeout(25000)})}catch{const e=new Error('Connection failed. No successful recording is confirmed. Retry the same action.');e.network=true;throw e}
 let result;try{result=await response.json()}catch{const e=new Error('The server response could not be confirmed. Retry the same action.');e.network=true;throw e}
 if(!response.ok){const e=new Error(result.error||'Request failed.');e.code=result.code;e.status=response.status;throw e}return result;
}
const query=()=>new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString();
async function init(){try{session=await api('/api/session');if(session.user){if(location.pathname.startsWith('/tap/'))tap=await api('/api/tap/'+encodeURIComponent(location.pathname.split('/')[2]));await load();if(tap||!isManager())view='Clock station'}render()}catch(e){root.innerHTML=`<main class="layout-error"><div class="brand">◷ ShiftTap</div><h1>Unable to open this page</h1><p>${h(e.message)}</p><button class="primary" data-action="reload">Try again</button><a class="text-button" href="/">Open dashboard</a></main>`}}
async function load(){data=await api('/api/data?'+query())}
async function refresh(){if(!session?.user||loading||document.querySelector('form.modal')||document.activeElement?.matches('input,select,textarea'))return;try{await load();render()}catch(e){if(e.status===401){session=await api('/api/session');data=null;render()}else flash(e.message,true)}}
function formInput(label,name,type='text',value='',required=true,extra=''){return `<label>${h(label)}<input name="${h(name)}" type="${h(type)}" value="${h(value)}" ${required?'required':''} ${extra}></label>`}
const options=(values,selected='',label='Choose…')=>`<option value="">${h(label)}</option>`+values.map(x=>`<option value="${h(x.id)}" ${x.id===selected?'selected':''}>${h(x.name)}</option>`).join('');
const select=(label,name,values,selected='',required=true)=>`<label>${h(label)}<select name="${h(name)}" ${required?'required':''}>${options(values,selected)}</select></label>`;
function authScreen(){
 const params=new URLSearchParams(location.search),flow=params.get('flow'),value=params.get('token');
 if(value){history.replaceState({},'',location.pathname);modal={type:'complete',token:value};}
 const mode=modal?.type==='complete'?'complete':session?.mfa_required?'mfa':modal?.type==='forgot'?'forgot':'login';
 const titles={login:'Welcome back.',forgot:'Reset your password.',complete:'Secure your account.',mfa:'One more step.'};
 root.innerHTML=`<main class="auth-page"><section class="auth-art"><div class="brand">◷ ShiftTap</div><div><div class="eyebrow">YOUR STORES. YOUR PEOPLE.</div><h1>Every shift.<br>One clear view.</h1><p>Simple clocking for your team. A connected view of attendance for you.</p><div class="lines">◷ ⌖ ▦</div></div><small>Independent attendance software · Hosted by your business</small></section><section class="auth-wrap"><form class="auth-form" data-form="${mode}"><div class="brand">◷ ShiftTap</div><h1>${titles[mode]}</h1><p>${mode==='login'?'Sign in with your staff or manager account.':mode==='mfa'?'Enter a code from your authenticator or one unused recovery code.':mode==='complete'?'Choose a password to activate or recover your account.':'Enter your account email. We’ll send a reset or activation link.'}</p>${mode==='mfa'?formInput('Verification or recovery code','code','text','','true','autocomplete="one-time-code"'):mode==='complete'?formInput('New password','password','password','','true','minlength="12" maxlength="128" autocomplete="new-password"')+formInput('Confirm password','confirm','password','','true','minlength="12" maxlength="128" autocomplete="new-password"'):formInput('Email','email','email','','true','autocomplete="username"')+(mode==='login'?formInput('Password','password','password','','true','autocomplete="current-password" maxlength="128"'):'')}<div class="error-text" id="form-error" role="alert"></div><button class="primary">${mode==='login'?'Sign in →':mode==='mfa'?'Verify →':mode==='complete'?'Save password':'Send email'}</button>${mode==='login'?'<button type="button" class="text-button" data-action="forgot">Forgot password or need a new activation email?</button>':'<button type="button" class="text-button" data-action="back-login">Back to sign in</button>'}<p class="muted">Staff accounts are invitation-only. Contact your manager if you haven’t received an invitation.</p></form></section></main>`;
}
function render(){
 if(new URLSearchParams(location.search).has('token')||modal?.type==='complete'){authScreen();return}
 if(!session?.user){authScreen();return}
 if(!data)return;
 const nav=isManager()?['Overview','Locations','Team','Timesheets','Requests','Clock station','Settings']:['Clock station','Timesheets','Requests','Settings'];
 const info={Overview:'See who’s working and what needs your attention.',Locations:'Your stores and their dedicated NFC clocking links.',Team:'Invite your people and assign their stores.',Timesheets:'Actual attendance hours. No wages or automatic rounding.',Requests:'Review correction requests and clocking exceptions.','Clock station':'Tap your store’s NFC tag, then confirm your action.',Settings:'Manage account security and attendance settings.'};
 root.innerHTML=`<div class="shell"><aside><a class="brand" href="/">◷ <span>ShiftTap<span class="brand-sub">STORE OPERATIONS</span></span></a><div class="workspace">YOUR WORKSPACE<strong>All your stores. One place.</strong></div><nav>${nav.map(v=>`<button class="nav ${view===v?'active':''}" data-action="view" data-view="${h(v)}" title="${h(v)}"><span>${({Overview:'▦',Locations:'⌖',Team:'♙',Timesheets:'▤',Requests:'☷','Clock station':'◷',Settings:'⚙'})[v]}</span><span class="nav-label">${h(v)}</span></button>`).join('')}</nav><div class="side-bottom"><span class="avatar">${h(session.user.name[0])}</span><div><strong>${h(session.user.name)}</strong><small>${h(session.user.role)}</small><button class="text-button" data-action="logout">Sign out</button></div></div></aside><main><header><div class="crumb">Workspace <span>/</span> ${h(view)}</div><div class="top-actions"><span class="muted">${h(session.user.email)}</span><button class="text-button" data-action="refresh">↻ Refresh</button><button class="text-button" data-action="logout">Sign out</button></div></header><section class="content"><div class="heading"><div><div class="eyebrow">STORE ATTENDANCE · YOUR BUSINESS</div><h1>${view==='Overview'?'Your stores, in sync.':h(view)}</h1><p>${h(info[view])}</p></div><div class="heading-actions">${view==='Locations'&&isOwner()?'<button class="primary" data-action="store-new">＋ Add location</button>':view==='Team'&&isManager()?'<button class="primary" data-action="staff-new">＋ Invite staff</button>':view==='Timesheets'&&isManager()?'<button class="outline" data-action="manual">＋ Manual shift</button>':''}</div></div>${pending?'<div class="banner">A clock action has not been confirmed. Retry it before recording another action. <button class="text-button" data-action="retry-clock">Retry '+h(pending.action)+'</button></div>':''}${content()}<footer>ShiftTap <span>Independent hosting · Attendance hours only</span></footer></section></main></div>`;
}
function filterBar(){return `<div class="filters"><select data-filter="store_id" aria-label="Filter by store"><option value="">All locations</option>${data.stores.map(s=>`<option value="${h(s.id)}" ${filters.store_id===s.id?'selected':''}>${h(s.name)}</option>`).join('')}</select>${view==='Timesheets'?`<select data-filter="user_id" aria-label="Filter by staff"><option value="">All visible staff</option>${data.users.map(u=>`<option value="${h(u.id)}" ${filters.user_id===u.id?'selected':''}>${h(u.name)}</option>`).join('')}</select><label>From <input type="date" data-filter="from" value="${h(filters.from)}"></label><label>To <input type="date" data-filter="to" value="${h(filters.to)}"></label>`:''}${isManager()?`<a class="outline" href="/api/export.csv?${h(query())}">↓ Export full CSV</a>`:''}</div>`}
function content(){
 if(view==='Overview'){
 const active=data.shifts.filter(s=>s.ended===null);
 return filterBar()+`<div class="stats">${[['On shift now',active.length,'Including staff on breaks'],['Worked today',hours(data.summary.daily_seconds)+' h','Current shifts are provisional'],['Worked this week',hours(data.summary.weekly_seconds)+' h','Monday to now, per store timezone'],['Active locations',data.stores.filter(s=>!s.archived).length,'Connected to your workspace']].map(([a,b,c])=>`<article class="stat"><span>${h(a)}</span><strong>${h(b)}</strong><small>${h(c)}</small></article>`).join('')}</div><div class="section-head"><h2>Location overview</h2><button class="text-button" data-action="view" data-view="Locations">Manage locations ↗</button></div><div class="location-grid">${data.stores.filter(s=>!s.archived&&(!filters.store_id||s.id===filters.store_id)).map(s=>`<article class="location"><div class="location-top"><div class="store-icon">⌖</div><span class="badge ${active.some(x=>x.store_id===s.id)?'green':''}">${active.some(x=>x.store_id===s.id)?'Staff on site':'No active shifts'}</span></div><h3>${h(s.name)}</h3><p>${h(s.address||'Address not added')}</p><div class="location-foot"><strong>${active.filter(x=>x.store_id===s.id).length} <span>on shift</span></strong><button class="text-button" data-action="store-timesheets" data-id="${h(s.id)}">View shifts →</button></div></article>`).join('')||empty('Add your first store','Create locations, invite staff, and put a tag at each entrance.',isOwner()?'<button class="primary" data-action="store-new">Add location</button>':'')}</div><div class="section-head"><h2>Live attendance</h2><span class="muted">Refreshes every 30 seconds</span></div>${shiftTable(active,true)}${data.shifts.some(s=>s.exception)?'<div class="info">Long-running shifts need review. No automatic clock-out has been invented.</div>':''}`;
 }
 if(view==='Locations')return `<div class="info">Write each store’s clocking URL to an ordinary NFC tag, or print its QR code. Opening the link does not record attendance. Static tags can be copied and do not prove physical presence.</div><div class="location-grid">${data.stores.map(s=>`<article class="location"><div class="location-top"><div class="store-icon">⌖</div><span class="badge ${s.archived?'orange':'green'}">${s.archived?'Archived':'Active'}</span></div><h3>${h(s.name)}</h3><p>${h(s.address||'Address not added')}<br>${h(s.timezone)} · Location ${s.location_required?'required':'optional'}</p><div class="tag-label">NFC CLOCKING LINK</div><input readonly aria-label="NFC link for ${h(s.name)}" value="${h(s.clock_url)}"><div class="card-actions"><button class="outline" data-action="copy" data-id="${h(s.id)}">Copy link</button><button class="outline" data-action="qr" data-id="${h(s.id)}">Print QR</button><a class="text-button" href="${h(s.clock_url)}">Open ↗</a><button class="text-button" data-action="store-edit" data-id="${h(s.id)}">Edit</button>${isOwner()?`<button class="text-button" data-action="store-state" data-id="${h(s.id)}" data-state="rotate">Revoke link</button><button class="text-button" data-action="store-state" data-id="${h(s.id)}" data-state="${s.archived?'restore':'archive'}">${s.archived?'Restore':'Archive'}</button>`:''}</div></article>`).join('')||empty('No locations yet','Add a location to create its NFC link.')}</div>`;
 if(view==='Team')return `<div class="panel table-wrap"><table><thead><tr><th>Staff member</th><th>Role / email</th><th>Stores</th><th>Status</th><th>Actions</th></tr></thead><tbody>${data.users.map(u=>`<tr><td><strong>${h(u.name)}</strong></td><td>${h(u.role)}<br><small>${h(u.email)}</small></td><td>${h(u.stores.map(id=>store(id)?.name).filter(Boolean).join(', ')||'No stores assigned')}</td><td><span class="badge ${u.active&&u.verified?'green':''}">${!u.active?'Inactive':u.verified?'Active':'Invitation pending'}</span></td><td><div class="actions-row">${isOwner()&&u.role!=='owner'?`<button class="text-button" data-action="staff-edit" data-id="${h(u.id)}">Edit</button><button class="text-button" data-action="staff-state" data-id="${h(u.id)}" data-state="${u.active?'deactivate':'activate'}">${u.active?'Deactivate':'Reactivate'}</button><button class="text-button" data-action="staff-state" data-id="${h(u.id)}" data-state="resend">Resend email</button>`:''}</div></td></tr>`).join('')}</tbody></table></div><div class="info">An invitation verifies the employee’s email and lets them choose their password. Deactivation revokes their sessions immediately. Historical records remain available.</div>`;
 if(view==='Timesheets')return filterBar()+`<div class="summary-line"><strong>${data.shifts.length} matching shifts</strong><span>${displayDuration(data.shifts.reduce((a,s)=>a+s.range_worked_seconds,0))} within selected range</span><small>Open shifts are provisional · CSV includes all matches</small></div>${shiftTable(data.shifts)}`;
 if(view==='Requests')return `<div class="review-list">${[...data.corrections.map(r=>({...r,kind:'corrections'})),...data.exceptions.map(r=>({...r,kind:'exceptions'}))].sort((a,b)=>b.created-a.created).map(r=>`<article class="review-card"><div class="section-head"><h3>${r.kind==='exceptions'?'Clocking exception · '+h(r.action):'Shift correction request'}</h3><span class="badge ${r.status==='pending'?'orange':'green'}">${h(r.status)}</span></div><p>${h(employee(r.user_id)?.name||'Staff')} · ${h(store(r.store_id)?.name)} · ${h(fmt(r.created,store(r.store_id)?.timezone,true))}</p><p>${h(r.reason)}</p>${r.resolution?`<p><strong>Resolution:</strong> ${h(r.resolution)}</p>`:''}${isManager()&&r.status==='pending'?`<button class="outline" data-action="review" data-id="${h(r.id)}" data-kind="${r.kind}">Review request</button>`:''}</article>`).join('')||empty('Nothing to review','Correction and location exception requests will appear here.')}</div><div class="info">Reviewing an exception does not create a punch. Use Manual shift to enter verified completed attendance, or correct an existing shift with a reason.</div>`;
 if(view==='Clock station'){
 if(!tap)return `<div class="empty panel"><span>◷</span><h3>Open your store’s clocking link</h3><p>Tap the NFC tag or scan the QR code at your assigned store.</p>${isManager()?'<button class="primary" data-action="view" data-view="Locations">Go to locations</button>':''}</div>`;
 const s=tap.store,active=data.shifts.find(x=>x.user_id===session.user.id&&x.ended===null),mismatch=active&&active.store_id!==s.id;
 return `<div class="clock-layout"><article class="clock-card"><div class="eyebrow">${h(s.name)}</div><div class="big-time">${h(fmt(data.now,s.timezone))}</div><p>${h(s.timezone)} · ${h(session.user.name)}</p><div class="shift-state"><span class="dot ${active?'':'grey'}"></span>${active?active.on_break?'On break':'Clocked in at '+h(fmt(active.started,store(active.store_id)?.timezone)):'Ready to clock in'}${active?`<small>${h(store(active.store_id)?.name)} · ${displayDuration(active.worked_seconds)} worked</small>`:''}</div>${mismatch?'<div class="alert error">Your open shift is at another store. Use that store’s link to clock out first.</div>':`<button class="clock-action ${active?'dark':''}" data-action="clock" data-clock="${active?'out':'in'}" ${pending||loading?'disabled':''}>${loading?'Recording…':active?'Clock out ↗':'Clock in →'}</button>${active?`<button class="outline full" data-action="clock" data-clock="${active.on_break?'resume':'break'}" ${pending||loading?'disabled':''}>${active.on_break?'End break':'Start break'}</button>`:''}`}<button class="text-button" data-action="exception">Request a clocking exception</button><small class="muted">Server time is recorded after you confirm.</small></article><section class="clock-notes"><h2>A simple tap, every shift.</h2><p>Confirm your action here. Your phone’s clock is not used for the timestamp.</p><ol><li><strong>Tap or scan at the store</strong><p>Sign in once; your session stays secure.</p></li><li><strong>Confirm your action</strong><p>Choose paid or unpaid when starting a break.</p></li><li><strong>Check the confirmation</strong><p>A success message appears only after the server saves.</p></li></ol><div class="info">${s.location_required?'This store requires location verification when you clock. Location is requested only for your action; there is no continuous tracking. Device location can be spoofed.':'Location verification is disabled at this store. Static NFC links can be copied; a tap does not prove that you are on site.'}</div></section></div>`;
 }
 if(view==='Settings')return `<div class="settings-grid"><article class="panel settings-card"><h2>Account security</h2><p>${h(session.user.email)}</p><span class="badge ${session.mfa_enabled?'green':''}">${session.mfa_enabled?'Authenticator MFA enabled':'Authenticator MFA not enabled'}</span>${!session.mfa_enabled?'<p>Add a second factor, especially for the owner account. Keep the one-time recovery codes safe.</p><button class="primary" data-action="mfa">Set up MFA</button>':''}<button class="text-button" data-action="reset-self">Send password reset email</button></article>${isOwner()?`<form class="panel settings-card" data-form="settings"><h2>Attendance and retention</h2>${formInput('Flag open shifts after (hours)','long_shift_hours','number',data.settings.long_shift_hours,true,'min="4" max="72"')}${formInput('Attendance retention days (0 = keep)','retention_days','number',data.settings.retention_days,true,'min="0" max="36500"')}${formInput('Location reading retention days','location_retention_days','number',data.settings.location_retention_days,true,'min="1" max="3650"')}${formInput('Encrypted backup retention days','backup_retention_days','number',data.settings.backup_retention_days,true,'min="7" max="3650"')}<p>Attendance deletion is disabled by default. When enabled (minimum 365 days), only completed, approved shifts without pending correction requests are purged. Immutable audit history is retained separately.</p><button class="primary">Save settings</button></form>`:''}<article class="panel settings-card"><h2>Backups and ownership</h2><p>The scheduled maintenance service creates an encrypted backup at least every 24 hours. Your server operator must configure off-server copies and test restores. See the included deployment guide.</p><p>There is no ChatGPT hosting, database or sign-in dependency. This application does not calculate wages.</p></article></div>`;
 return '';
}
function empty(title,description,actions=''){return `<div class="empty wide"><h3>${h(title)}</h3><p>${h(description)}</p>${actions}</div>`}
function shiftTable(records,live=false){
 const count=Math.ceil(records.length/50),display=live?records:records.slice(page*50,(page+1)*50);
 return `<div class="panel table-wrap"><table><thead><tr><th>Staff / store</th><th>Clock in</th><th>Clock out / status</th><th>Unpaid break</th><th>Worked</th><th>Approval</th><th>Actions</th></tr></thead><tbody>${display.map(s=>`<tr><td><div class="person"><span class="avatar">${h(s.employee_name[0])}</span><div><strong>${h(s.employee_name)}</strong><small>${h(s.store_name)} · ${h(s.timezone)}</small></div></div></td><td>${h(fmt(s.started,s.timezone,true))}</td><td>${s.ended===null?`<span class="badge ${s.exception?'orange':'green'}">${s.on_break?'On break':'Open / provisional'}</span>${s.exception?'<small class="error-text"><br>Needs review</small>':''}`:h(fmt(s.ended,s.timezone,true))}</td><td>${displayDuration(s.unpaid_seconds)}</td><td><strong>${displayDuration(s.worked_seconds)}</strong></td><td><span class="badge ${s.approval==='approved'?'green':''}">${h(s.approval)}</span></td><td><div class="actions-row">${isManager()?`<button class="text-button" data-action="correct" data-id="${h(s.id)}">Correct</button><button class="text-button" data-action="audit" data-id="${h(s.id)}">History</button>${s.ended!==null&&s.approval!=='approved'?`<button class="text-button" data-action="approve" data-id="${h(s.id)}">Approve</button>`:''}`:''}${s.user_id===session.user.id?`<button class="text-button" data-action="correction-request" data-id="${h(s.id)}">Request correction</button>`:''}</div></td></tr>`).join('')}</tbody></table>${!records.length?empty(live?'No one is clocked in':'No shifts to show',live?'Active shifts will appear here.':'Record a shift or adjust your filters.') :!live&&count>1?`<div class="pagination"><button class="outline" data-action="page" data-page="${page-1}" ${page===0?'disabled':''}>Previous</button><span>${page+1} / ${count}</span><button class="outline" data-action="page" data-page="${page+1}" ${page+1===count?'disabled':''}>Next</button></div>`:''}</div>`;
}
function openModal(type,value={}){
 modal={type,...value};let title='',body='';const activeStores=data?.stores.filter(s=>!s.archived)||[];
 if(type==='store'){
  const s=value.store||{};title=s.id?'Edit location':'Add location';
  body=`<div class="fields">${formInput('Store name','name','text',s.name||'')}${formInput('Address','address','text',s.address||'',false)}${formInput('IANA timezone','timezone','text',s.timezone||'Australia/Sydney')}<label class="check"><input type="checkbox" name="location_required" ${s.location_required?'checked':''}><span>Require location for clock actions</span></label>${formInput('Latitude','latitude','number',s.latitude??'',false,'step="any" min="-90" max="90"')}${formInput('Longitude','longitude','number',s.longitude??'',false,'step="any" min="-180" max="180"')}${formInput('Allowed radius (metres)','radius','number',s.radius||150,true,'min="10" max="10000"')}${formInput('Maximum GPS uncertainty (metres)','max_accuracy','number',s.max_accuracy||100,true,'min="1" max="1000"')}</div><p>Coordinates are validated on the server. Verification requires the location uncertainty circle to fit inside the permitted radius. GPS can still be spoofed.</p>`;
 }else if(type==='staff'){
  const u=value.user||{};title=u.id?'Edit staff member':'Invite staff';body=formInput('Full name','name','text',u.name||'')+formInput('Email','email','email',u.email||'',true,u.id?'readonly':'')+`<label>Role<select name="role"><option value="staff">Staff</option>${isOwner()?`<option value="manager" ${u.role==='manager'?'selected':''}>Store manager</option>`:''}</select></label><label>Assigned stores</label><div class="check-list">${activeStores.map(s=>`<label class="check"><input type="checkbox" name="stores" value="${h(s.id)}" ${u.stores?.includes(s.id)?'checked':''}><span>${h(s.name)}</span></label>`).join('')||'<p>Add a store first.</p>'}</div>`;
 }else if(type==='qr'){const s=value.store;title=s.name;body=`<p>Tap or scan to clock your shift.</p><img class="qr-preview" src="${h(s.qr_url)}" alt="Clocking QR code for ${h(s.name)}"><p>${h(s.address)}</p><p>Sign in, then confirm Clock In or Clock Out.</p><button class="primary" type="button" data-action="print">Print QR sign</button>`}
 else if(type==='correct'||type==='manual'){
  const s=value.shift;title=type==='correct'?'Correct recorded attendance':'Add a verified manual shift';
  body=`<p>Enter timestamps with explicit timezone offsets, for example 2026-10-07T09:00:00+11:00. This avoids ambiguous daylight-saving times.</p>${type==='manual'?select('Staff member','user_id',data.users.filter(u=>u.role!=='owner'))+select('Store','store_id',activeStores):`<p><strong>${h(s.employee_name)}</strong> · ${h(s.store_name)}</p>`}${formInput('Start timestamp (ISO with offset)','started','text',s?iso(s.started,s.timezone):'')}${formInput('End timestamp (ISO with offset)','ended','text',s?.ended?iso(s.ended,s.timezone):'')}<label>Breaks</label><div id="break-editor">${(s?.breaks||[]).map(b=>breakRow(b,s.timezone)).join('')}</div><button type="button" class="outline" data-action="add-break">＋ Add break</button><p>Keep every break that was taken. Paid breaks count toward worked hours; unpaid breaks are deducted.</p><label>Required reason<textarea required name="reason" minlength="5" maxlength="1000"></textarea></label><p>Original values remain in the immutable audit history. Corrected shifts return to pending approval.</p>`;
 }else if(type==='break'){title='Start a break';body='<label>Break type<select name="paid"><option value="false">Unpaid break</option><option value="true">Paid break</option></select></label><p>Choose the break type approved for your shift.</p>'}
 else if(type==='request'){title='Request a shift correction';body='<label>Explain the required correction<textarea required name="reason" maxlength="1000" placeholder="Which time is wrong, and what should it be?"></textarea></label>'}
 else if(type==='exception'){title='Request a clocking exception';body=`<p>No punch will be recorded from this request. A manager must verify attendance and enter or correct a completed shift.</p><label>Requested action<select name="action"><option value="in">Clock in</option><option value="out">Clock out</option><option value="break">Start break</option><option value="resume">End break</option></select></label><label>Reason<textarea name="reason" required maxlength="1000" placeholder="Location permission was denied, or the GPS reading is unreliable…"></textarea></label>`}
 else if(type==='review'){title='Review request';body=`<p>Verify attendance, then use Manual shift or Correct to update attendance separately. This form records only the review.</p><label>Decision<select name="status"><option value="resolved">Resolved</option><option value="rejected">Rejected</option></select></label><label>Resolution / reason<textarea name="resolution" required maxlength="1000"></textarea></label>`}
 else if(type==='mfa'){title='Set up authenticator MFA';body=formInput('Confirm your password','password','password','','true','autocomplete="current-password"')+'<p>You will receive a secret to add to your authenticator, then confirm a six-digit code.</p>'}
 else if(type==='mfa-confirm'){title='Confirm your authenticator';body=`<p>Add this secret to your authenticator as a time-based, six-digit SHA-1 account named ShiftTap. Do not share it.</p><code class="secret">${h(value.secret)}</code>${formInput('Six-digit authenticator code','code','text','','true','inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code"')}`}
 else if(type==='recovery'){title='Save your recovery codes';body=`<p>Save these codes in your password manager. Each can be used once instead of an authenticator code. They will not be shown again.</p><ul class="codes">${value.codes.map(c=>`<li>${h(c)}</li>`).join('')}</ul>`}
 else if(type==='audit'){title='Immutable shift history';body=value.records.map(r=>`<article class="audit-record"><strong>${h(r.kind)}</strong><p>${h(fmt(r.created,'Australia/Sydney',true))} · Actor ${h(r.actor_id)}</p><p>${h(r.reason)}</p><details><summary>Original and resulting values</summary><pre>${h(JSON.stringify({before:r.before_json?JSON.parse(r.before_json):null,after:r.after_json?JSON.parse(r.after_json):null},null,2))}</pre></details></article>`).join('')||'<p>No audit records.</p>'}
 dialogs.innerHTML=`<div class="modal-backdrop"><form class="modal ${type==='qr'?'print-qr':''}" data-form="${h(type)}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="section-head"><h2 id="modal-title">${h(title)}</h2><button type="button" class="text-button" aria-label="Close dialog" data-action="close-modal">✕</button></div>${body}<div class="error-text dialog-error" role="alert"></div>${['qr','audit','recovery'].includes(type)?'<button class="outline full" type="button" data-action="close-modal">Done</button>':'<div class="card-actions"><button class="outline" type="button" data-action="close-modal">Cancel</button><button class="primary">'+(type==='staff'?'Save staff':type==='mfa'?'Continue':'Save')+'</button></div>'}</form></div>`;
 dialogs.querySelector('input,textarea,button')?.focus();
}
function breakRow(b={},tz='Australia/Sydney'){return `<div class="break-row"><div class="fields">${formInput('Break start (ISO with offset)','break_started','text',b.started?iso(b.started,tz):'')}${formInput('Break end (ISO with offset)','break_ended','text',b.ended?iso(b.ended,tz):'')}<label>Break type<select name="break_paid"><option value="false">Unpaid</option><option value="true" ${b.paid?'selected':''}>Paid</option></select></label><button type="button" class="text-button" data-action="remove-break">Remove break</button></div></div>`}
function iso(stamp,tz){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(stamp*1000));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));const offset=new Intl.DateTimeFormat('en-US',{timeZone:tz,timeZoneName:'longOffset'}).formatToParts(new Date(stamp*1000)).find(x=>x.type==='timeZoneName').value.replace('GMT','')||'+00:00';return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}${offset}`}
function parseStamp(s){if(!/T.*(?:Z|[+-]\d{2}:\d{2})$/.test(s)||!Number.isFinite(Date.parse(s)))throw Error('Use a full ISO timestamp with Z or a timezone offset.');return Math.floor(Date.parse(s)/1000)}
function closeModal(){dialogs.replaceChildren();modal=null}
async function mutate(url,payload,message='Saved successfully.'){await api(url,payload);await load();closeModal();render();flash(message)}
function geo(){return new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(Error('Location is unavailable in this browser.'));return}navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),()=>reject(Error('Location could not be read. Use the exception request if permission is denied or GPS is unavailable.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
async function punch(action,paid=false){
 if(loading)return;loading=true;render();
 try{
  if(!pending){lastLocation=null;if(tap.store.location_required)lastLocation=await geo();pending={key:crypto.randomUUID(),store_id:tap.store.id,tag:tap.tag,action,paid,location:lastLocation}}
  const result=await api('/api/clock',pending);pending=null;await load();render();flash(({in:'Clocked in',out:'Clocked out',break:'Break started',resume:'Break ended'})[result.action]+' at '+fmt(result.timestamp,tap.store.timezone)+'. Recorded successfully.');
 }catch(e){if(!e.network)pending=null;render();flash(e.message,true);if(e.code==='location_exception')openModal('exception')}
 finally{loading=false;render()}
}
document.addEventListener('click',async e=>{
 const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const action=el.dataset.action,id=el.dataset.id;
 try{
  if(action==='view'){view=el.dataset.view;page=0;render()}
  else if(action==='reload')location.reload();
  else if(action==='refresh')await refresh();
  else if(action==='forgot'){modal={type:'forgot'};render()}
  else if(action==='back-login'){await api('/api/logout',{});modal=null;session=await api('/api/session');render()}
  else if(action==='logout'){await api('/api/logout',{});session=await api('/api/session');data=null;tap=null;pending=null;modal=null;dialogs.replaceChildren();render()}
  else if(action==='store-new')openModal('store');
  else if(action==='store-edit')openModal('store',{store:store(id)});
  else if(action==='staff-new')openModal('staff');
  else if(action==='staff-edit')openModal('staff',{user:employee(id)});
  else if(action==='store-state'){if(confirm(el.dataset.state==='rotate'?'Revoke this store’s current NFC link? Existing tags and QR signs will need to be replaced.':el.dataset.state+' this store?'))await mutate('/api/stores/'+id+'/state',{action:el.dataset.state},'Store updated.');}
  else if(action==='staff-state'){if(confirm(el.dataset.state==='deactivate'?'Deactivate this staff member and revoke their login sessions?':'Confirm '+el.dataset.state+' for this staff member?'))await mutate('/api/users/'+id+'/state',{action:el.dataset.state},el.dataset.state==='resend'?'Email queued.':'Account updated.');}
  else if(action==='copy'){await navigator.clipboard.writeText(store(id).clock_url);flash('NFC link copied.');}
  else if(action==='qr')openModal('qr',{store:store(id)});
  else if(action==='print')window.print();
  else if(action==='close-modal')closeModal();
  else if(action==='add-break')document.querySelector('#break-editor').insertAdjacentHTML('beforeend',breakRow());
  else if(action==='remove-break')el.closest('.break-row').remove();
  else if(action==='store-timesheets'){filters.store_id=id;view='Timesheets';page=0;await load();render()}
  else if(action==='page'){page=Number(el.dataset.page);render()}
  else if(action==='manual')openModal('manual');
  else if(action==='correct')openModal('correct',{shift:data.shifts.find(s=>s.id===id)});
  else if(action==='correction-request')openModal('request',{shift_id:id});
  else if(action==='approve'){const s=data.shifts.find(s=>s.id===id);await mutate('/api/shifts/'+id+'/approve',{version:s.version},'Timesheet approved.');}
  else if(action==='review')openModal('review',{id,kind:el.dataset.kind});
  else if(action==='audit'){const result=await api('/api/shifts/'+id+'/audit');openModal('audit',result)}
  else if(action==='mfa')openModal('mfa');
  else if(action==='reset-self'){await api('/api/password/request',{email:session.user.email});flash('If your account is active, a reset email will arrive shortly.');}
  else if(action==='exception')openModal('exception');
  else if(action==='retry-clock')await punch(pending.action,pending.paid);
  else if(action==='clock'){if(el.dataset.clock==='break'){openModal('break')}else await punch(el.dataset.clock)}
 }catch(error){flash(error.message,true)}
});
document.addEventListener('change',async e=>{if(e.target.dataset.filter){filters[e.target.dataset.filter]=e.target.value;page=0;try{await load();render()}catch(error){flash(error.message,true)}}});
document.addEventListener('submit',async e=>{
 const form=e.target;if(!form.dataset.form)return;e.preventDefault();const f=new FormData(form),b=Object.fromEntries(f.entries()),type=form.dataset.form,buttons=[...form.querySelectorAll('button')];buttons.forEach(x=>x.disabled=true);const error=form.querySelector('.error-text');if(error)error.textContent='';
 try{
  if(type==='login'){await api('/api/login',b);session=await api('/api/session');if(session.user){await load();if(location.pathname.startsWith('/tap/')){tap=await api('/api/tap/'+encodeURIComponent(location.pathname.split('/')[2]));view='Clock station'}else if(!isManager())view='Clock station'}render();}
  else if(type==='mfa'&&!session.user){await api('/api/login/mfa',b);session=await api('/api/session');await load();if(location.pathname.startsWith('/tap/')){tap=await api('/api/tap/'+encodeURIComponent(location.pathname.split('/')[2]));view='Clock station'}render()}
  else if(type==='forgot'){await api('/api/password/request',b);flash('If an active account exists, an email will arrive shortly.');}
  else if(type==='complete'){if(b.password!==b.confirm)throw Error('Passwords do not match.');await api('/api/password/complete',{token:modal.token,password:b.password});modal=null;session=await api('/api/session');render();flash('Password saved. Sign in to continue.');}
  else if(type==='store'){b.location_required=f.has('location_required');b.id=modal.store?.id;await mutate('/api/stores',b);}
  else if(type==='staff'){b.stores=f.getAll('stores');b.id=modal.user?.id;await mutate('/api/users',b,b.id?'Staff updated.':'Invitation queued. Email delivery is handled by the maintenance service.');}
  else if(type==='correct'||type==='manual'){b.started=parseStamp(b.started);b.ended=parseStamp(b.ended);b.breaks=f.getAll('break_started').map((v,i)=>({started:parseStamp(v),ended:parseStamp(f.getAll('break_ended')[i]),paid:f.getAll('break_paid')[i]==='true'}));delete b.break_started;delete b.break_ended;delete b.break_paid;if(type==='correct'){b.shift_id=modal.shift.id;b.version=modal.shift.version}await mutate('/api/shifts/'+(type==='correct'?'correct':'manual'),b);}
   else if(type==='request'){await mutate('/api/corrections',{...b,shift_id:modal.shift_id},'Correction request submitted.');}
  else if(type==='exception'){await mutate('/api/exceptions',{...b,store_id:tap.store.id,tag:tap.tag,location:lastLocation},'Exception submitted. No punch was recorded.');}
  else if(type==='review'){await mutate('/api/review',{...b,id:modal.id,kind:modal.kind},'Review saved.');}
  else if(type==='settings'){for(const k of Object.keys(b))b[k]=Number(b[k]);if(b.retention_days&&!confirm('Enable automatic deletion of eligible approved attendance older than '+b.retention_days+' days? Audit history remains.'))return;await mutate('/api/settings',b);}
  else if(type==='mfa'){const r=await api('/api/mfa/start',b);openModal('mfa-confirm',r);}
  else if(type==='mfa-confirm'){const r=await api('/api/mfa/confirm',b);session=await api('/api/session');render();openModal('recovery',{codes:r.recovery_codes});}
  else if(type==='break'){const paid=b.paid==='true';closeModal();await punch('break',paid);}
 }catch(err){if(error)error.textContent=err.message;else flash(err.message,true)}finally{buttons.forEach(x=>x.disabled=false)}
});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='Tab'&&dialogs.firstChild){const list=[...dialogs.querySelectorAll('button,input,select,textarea,a[href]')].filter(x=>!x.disabled);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}});
window.addEventListener('offline',()=>flash('You are offline. Clock actions cannot be recorded until you reconnect.',true));
setInterval(refresh,30000);init();
